on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: csv lint
    steps:
    - uses: actions/checkout@v1
    - name: Install csvkit
      run: pip install csvkit
    - name: Validate CSV file with csvformat
      run: csvformat .shelldio/all_stations.txt > /dev/null
