on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: csv lint
    steps:
    - uses: actions/checkout@v1
    - name: Install csvkit
      run: pip install csvkit
    - name: Lint CSV file
      run: csvclean .shelldio/all_stations.txt
