name: CSV Lint

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install csvkit
        run: pip install csvkit
      - name: Validate CSV file with csvclean
        run: csvclean -n .shelldio/all_stations.txt
